### ISSUE TITLE
Error creating resources in version 0.1.15

### ISSUE THREAD

**Issue by wanisfahmyDE** [fourplusone/terraform-provider-jira#39]
Hello,

I am trying to use the latest release 0.1.15, my terraform version is 0.15.4, Jira version is 8.13.5 on premise.

`Error: Plugin did not respond
│
│   with jira_issue.example,
│   on accounts.tf line 33, in resource "jira_issue" "example":
│   33: resource "jira_issue" "example" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-jira_v0.1.15 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1918447]

goroutine 69 [running]:
github.com/fourplusone/terraform-provider-jira/jira.resourceIssueCreate(0xc0001ad3b0, 0x1a719e0, 0xc0001bc0a8, 0x2, 0x2557ac0)
	github.com/fourplusone/terraform-provider-jira/jira/resource_issue.go:151 +0xc87
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00019ec00, 0xc00008b7c0, 0xc00064f960, 0x1a719e0, 0xc0001bc0a8, 0x1a85a01, 0xc0000af2f8, 0xc0000c70b0)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/resource.go:305 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00019f200, 0xc0000b78e0, 0xc00008b7c0, 0xc00064f960, 0xc0000bf3a8, 0xc00012ecb8, 0x1a87760)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00012ea70, 0x1e2d660, 0xc0000c62d0, 0xc000047080, 0xc00012ea70, 0xc0000c62d0, 0xc000283a48)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/helper/plugin/grpc_provider.go:885 +0x882
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1b97ec0, 0xc00012ea70, 0x1e2d660, 0xc0000c62d0, 0xc000047020, 0x0, 0x1e2d660, 0xc0000c62d0, 0xc0000c81e0, 0x1c5)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00015a000, 0x1e374e0, 0xc000782900, 0xc000094700, 0xc000406e40, 0x251dcc0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc00015a000, 0x1e374e0, 0xc000782900, 0xc000094700, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000038240, 0xc00015a000, 0x1e374e0, 0xc000782900, 0xc000094700)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa1

Error: The terraform-provider-jira_v0.1.15 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
`

any thoughts regarding that?

**Comment by wanisfahmyDE** [comment]
the issue was with go:
https://github.com/golang/go/issues/12524
closing issue
