### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mahsoud** [fourplusone/terraform-provider-jira#54]
Stack trace from the terraform-provider-jira_v0.1.14 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd0c063]
goroutine 46 [running]:
github.com/fourplusone/terraform-provider-jira/jira.resourceIssueCreate(0xc00043d180, 0xe631e0, 0xc00070c3e8, 0x2, 0x1939fc0)
	github.com/fourplusone/terraform-provider-jira/jira/resource_issue.go:116 +0x8f3
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0001c8c00, 0xc000130f00, 0xc00038f5e0, 0xe631e0, 0xc00070c3e8, 0xe76a01, 0xc0004e3528, 0xc000164d50)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/resource.go:305 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0001c9180, 0xc00015d8e0, 0xc000130f00, 0xc00038f5e0, 0xc000160748, 0xc00070c7c0, 0xe78720)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ea78, 0x[121](https://git.-.-/-/-/-/-/jobs/4393195#L121)98c0, 0xc0001640f0, 0xc000134a20, 0xc00000ea78, 0xc0001640f0, 0xc000936a48)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/helper/plugin/grpc_provider.go:885 +0x882
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xf862e0, 0xc00000ea78, 0x12198c0, 0xc0001640f0, 0xc0001349c0, 0x0, 0x12198c0, 0xc0001640f0, 0xc00013d080, 0x527)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000190000, 0x[122](https://git.-.-/-/-/-/-/4393195#L122)34e0, 0xc000702900, 0xc000174600, 0xc0000cd7d0, 0x18ffbc0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc000190000, 0x12234e0, 0xc000702900, 0xc000174600, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:[127](https://git.-.-/-/-/-/-/4393195#L127)5 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00051c1f0, 0xc000190000, 0x12234e0, 0xc000702900, 0xc000174600)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
Error: The terraform-provider-jira_v0.1.14 plugin crashed!

**Comment by mahsoud** [comment]
Stack trace from the terraform-provider-jira_v0.1.15 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd19db7]
goroutine 32 [running]:
github.com/fourplusone/terraform-provider-jira/jira.resourceIssueCreate(0xc00044c310, 0xe738a0, 0xc00000e450, 0x2, 0x1956060)
	github.com/fourplusone/terraform-provider-jira/jira/resource_issue.go:151 +0xc87
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0000da380, 0xc0002531d0, 0xc00000dee0, 0xe738a0, 0xc00000e450, 0xe87701, 0xc000423898, 0xc000294de0)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/resource.go:305 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000da980, 0xc0004fd8e0, 0xc0002531d0, 0xc00000dee0, 0xc00028da68, 0xc00000e850, 0xe89380)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e078, 0x122ec40, 0xc000294000, 0xc000249500, 0xc00000e078, 0xc000294000, 0xc000933a48)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/helper/plugin/grpc_provider.go:885 +0x882
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xf995a0, 0xc00000e078, 0x122ec40, 0xc000294000, 0xc0002494a0, 0x0, 0x122ec40, 0xc000294000, 0xc00027cb00, 0x547)
	github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007902c0, 0x1238860, 0xc000802f00, 0xc0001b6300, 0xc00041baa0, 0x191bc00, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc0007902c0, 0x1238860, 0xc000802f00, 0xc0001b6300, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00059a1f0, 0xc0007902c0, 0x1238860, 0xc000802f00, 0xc0001b6300)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
Error: The terraform-provider-jira_v0.1.15 plugin crashed!
